// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

#ifndef PROTOBUF_packet_2eproto__INCLUDED
#define PROTOBUF_packet_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace PB {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_packet_2eproto();
void protobuf_AssignDesc_packet_2eproto();
void protobuf_ShutdownFile_packet_2eproto();

class Packet;

// ===================================================================

class Packet : public ::google::protobuf::Message {
 public:
  Packet();
  virtual ~Packet();
  
  Packet(const Packet& from);
  
  inline Packet& operator=(const Packet& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Packet& default_instance();
  
  void Swap(Packet* other);
  
  // implements Message ----------------------------------------------
  
  Packet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Packet& from);
  void MergeFrom(const Packet& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 version = 1;
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 1;
  inline ::google::protobuf::uint32 version() const;
  inline void set_version(::google::protobuf::uint32 value);
  
  // required uint32 command = 2;
  inline bool has_command() const;
  inline void clear_command();
  static const int kCommandFieldNumber = 2;
  inline ::google::protobuf::uint32 command() const;
  inline void set_command(::google::protobuf::uint32 value);
  
  // optional bytes serialized = 3;
  inline bool has_serialized() const;
  inline void clear_serialized();
  static const int kSerializedFieldNumber = 3;
  inline const ::std::string& serialized() const;
  inline void set_serialized(const ::std::string& value);
  inline void set_serialized(const char* value);
  inline void set_serialized(const void* value, size_t size);
  inline ::std::string* mutable_serialized();
  inline ::std::string* release_serialized();
  
  // @@protoc_insertion_point(class_scope:PB.Packet)
 private:
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_command();
  inline void clear_has_command();
  inline void set_has_serialized();
  inline void clear_has_serialized();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 version_;
  ::google::protobuf::uint32 command_;
  ::std::string* serialized_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_packet_2eproto();
  friend void protobuf_AssignDesc_packet_2eproto();
  friend void protobuf_ShutdownFile_packet_2eproto();
  
  void InitAsDefaultInstance();
  static Packet* default_instance_;
};
// ===================================================================


// ===================================================================

// Packet

// required uint32 version = 1;
inline bool Packet::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Packet::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Packet::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Packet::clear_version() {
  version_ = 0u;
  clear_has_version();
}
inline ::google::protobuf::uint32 Packet::version() const {
  return version_;
}
inline void Packet::set_version(::google::protobuf::uint32 value) {
  set_has_version();
  version_ = value;
}

// required uint32 command = 2;
inline bool Packet::has_command() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Packet::set_has_command() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Packet::clear_has_command() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Packet::clear_command() {
  command_ = 0u;
  clear_has_command();
}
inline ::google::protobuf::uint32 Packet::command() const {
  return command_;
}
inline void Packet::set_command(::google::protobuf::uint32 value) {
  set_has_command();
  command_ = value;
}

// optional bytes serialized = 3;
inline bool Packet::has_serialized() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Packet::set_has_serialized() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Packet::clear_has_serialized() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Packet::clear_serialized() {
  if (serialized_ != &::google::protobuf::internal::kEmptyString) {
    serialized_->clear();
  }
  clear_has_serialized();
}
inline const ::std::string& Packet::serialized() const {
  return *serialized_;
}
inline void Packet::set_serialized(const ::std::string& value) {
  set_has_serialized();
  if (serialized_ == &::google::protobuf::internal::kEmptyString) {
    serialized_ = new ::std::string;
  }
  serialized_->assign(value);
}
inline void Packet::set_serialized(const char* value) {
  set_has_serialized();
  if (serialized_ == &::google::protobuf::internal::kEmptyString) {
    serialized_ = new ::std::string;
  }
  serialized_->assign(value);
}
inline void Packet::set_serialized(const void* value, size_t size) {
  set_has_serialized();
  if (serialized_ == &::google::protobuf::internal::kEmptyString) {
    serialized_ = new ::std::string;
  }
  serialized_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Packet::mutable_serialized() {
  set_has_serialized();
  if (serialized_ == &::google::protobuf::internal::kEmptyString) {
    serialized_ = new ::std::string;
  }
  return serialized_;
}
inline ::std::string* Packet::release_serialized() {
  clear_has_serialized();
  if (serialized_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = serialized_;
    serialized_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace PB

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_packet_2eproto__INCLUDED
